### ISSUE TITLE
stylelint.io next steps

### ISSUE THREAD

**Issue by nicinabox** [stylelint/stylelint.github.io#3]
## Architecture

Assuming Github Pages hosting I think Jekyll will probably be the easiest way to start this off. Ideally this can be swapped with something else later without impacting the publishing process too much.

## Publishing

To avoid maintaining docs in multiple places we'd like the docs source to remain in the primary repo (stylelint/stylelint). We need to automate pulling in the docs structure in a build step so it can be published easily and frequently (CI maybe?).

## Linting

Dogfood stylelint.

## New features

* Interactive demo/playground
* Docs search
* Server rendered pages

## Milestones

I'd like to have a working version of the current docs deployed before anything else. After that it should be straightforward to head up the playground and search. They don't depend on each other, so it's possible they could be worked on by different people at the same time.

## To be determined

* [x] Do we want to maintain docs for older versions? How does that impact url structure?
* [ ] Visual design changes?
* [x] Preferred CSS style, tools?
* [x] Code reviews? 
* [x] Work off branch of stylelint repo or new fork? I'd like if the process was visible.

**Comment by MoOx** [comment]
imo keeping the website in the project itself can make maintenance easier.

**Comment by DanGamble89** [comment]
RE: Preferred CSS style. Is there any merit to trying to create a Stylelint based CSS style? I know you mention SuitCSS on the homepage and link to a premade by them. But i was wondering if there is any room for something that is the CSS equivalent to http://standardjs.com/

**Comment by nicinabox** [comment]
@MoOx is github pages the home for the foreseeable future? We could use a gh-pages branch and copy the docs directory with git.

**Comment by MoOx** [comment]
I am not in charge here, I just think using another repo is harder for the docs maintenance. A website in the project repo seems a better idea to me.

**Comment by MoOx** [comment]
(it can totally use github pages).

**Comment by nicinabox** [comment]
@jeddy3 @davidtheclark could you guys answer some of the questions at the top when you get a chance?

**Comment by davidtheclark** [comment]
> Architecture

As long as the code stays as simple as possible, I'm fine with using whatever tech is preferred by whoever is doing the primary work on the site, so I'm fine with Jekyll. I'm familiar with it, also, so that's a plus.

> imo keeping the website in the project itself can make maintenance easier.

I think I agree with @MoOx here. We just have to make sure the files necessary for docs don't clog up and confuse the repo.

> Linting & New Features & Milestones

All sounds great.

> Do we want to maintain docs for older versions? How does that impact url structure?

My guess is that that will add a fair amount of complexity. If it is simple, sure; but if too complex, I'd say it's not necessary. URL structure could be something like `stylelint.io/2.1.6/rules` or `stylelint.io/old/2.1.6/rules`.

> Visual design changes?

I'm open to any suggestions.

> Preferred CSS style, tools?

I myself like and use SuitCSS conventions for selectors. That's what I'd favor. 

As for the CSS linting itself, I'd be fine with using the SuitCSS config or with creating a new standard-style config (nice idea, @DanGamble89). 

> Code reviews?

Please submit work via PRs and we'll review each other's code.

> Work off branch of stylelint repo or new fork? I'd like if the process was visible.

I'd say create a new branch off stylelint master for parallel work on the website.

**Comment by davidtheclark** [comment]
@nicinabox I've added you as a collaborator to facilitate this.

**Comment by nicinabox** [comment]
Thanks.

**Architecture**

I'm going to move ahead with Jekyll for the ease of getting started and pre-existing shared knowledge.

**Doc versions** 
The simplest thing might be to just lave latest be deployed with links to previous tag versions on github. That way we're not alienated people who can't upgrade, especially at major versions. If they're browsable on github and accessible from the site that should be good enough to start.

**Site in the repo**
I like this idea. I'll go forward with creating PRs on the stylelint/stylelint repo.

**Comment by nicinabox** [comment]
I'm now realizing that docs will need front matter to be picked up by jekyll, Simply copying them in isn't enough.

**Comment by nicinabox** [comment]
There is now a proof of concept available. It's got default styles, but the main thing is the whirlygig that copies and parses the docs for use on the site.

Check it out: https://github.com/stylelint/stylelint/tree/gh-pages-next

**Comment by davidtheclark** [comment]
I'm hitting an error trying it out:

```
➜  stylelint git:(gh-pages-next) ✗ npm run docs

> @ docs /Users/davidclark/dev/stylelint
> npm run update-files && npm run process-docs


> @ update-files /Users/davidclark/dev/stylelint
> sh ./tasks/update-files.sh

git: 'co' is not a git command. See 'git --help'.

Did you mean one of these?
	commit
	clone
	log
```

**Comment by davidtheclark** [comment]
Also, I think that @jeddy3 uses Windows (is that right, or am I misremembering?), so we'll need any scripts to work cross-platform. I think for example the following won't:

```
rm -rf docs/src
mv src docs
rm -rf docs/src/rules/**/__tests__
rm -rf docs/src/rules/**/*.js
```

Might want to write a node script for that stuff?

**Comment by davidtheclark** [comment]
Thanks @nicinabox! Besides the comments above, I'm going to read the code and make inline comments in the commits, I think.

**Comment by davidtheclark** [comment]
Actually, I think the best way to do that is with a PR. Would you open up PR for that branch?

**Comment by nicinabox** [comment]
> I think the best way to do that is with a PR

I kinda screwed that up. There has to be an existing branch first before github will allow a comparison. Since this was a new branch with a new history it won't do PR for it as far as I can tell.

**Comment by davidtheclark** [comment]
Ooops, one more thought off the top of my head: Can we contain the docs files within a directory? One idea is to give the `docs/` dir would have `md/` and `jekyllSrc/`, or something similar ...

**Comment by nicinabox** [comment]
@davidtheclark wanna hop on gitter real quick?

**Comment by davidtheclark** [comment]
> I kinda screwed that up. There has to be an existing branch first before github will allow a comparison. Since this was a new branch with a new history it won't do PR for it as far as I can tell

Probably you could create a new branch without a new history and copy-paste your stuff? Ok, I'll hop on gitter.

**Comment by nicinabox** [comment]
`update-files` task should now be closer to cross-compatible. I haven't tested it on windows, but it's at least a step in the right direction.

Also fixed checking the first line for front matter.

Still need to figure out the best way to get a real PR going.

**Comment by jeddy3** [comment]
> Also, I think that @jeddy3 uses Windows (is that right, or am I misremembering?),

That's right, I was using Windows for most of last year. My laptop finally gave up the ghost a couple of months ago and I've been using a mac since. However, I think it's worth persevering with making the build cross-compatible as I know postcss (and therefore stylelint) is popular with the windows crowd.

**Comment by nicinabox** [comment]
Might be possible to use a CI server to do automatic builds for gh-pages when master gets pushed. Then no one has to hassle with regularly updating the site.

**Comment by MoOx** [comment]
That doc might help you http://moox.io/statinamic/docs/usage/gh-pages/ (and should works with whatever engine you use)

**Comment by davidtheclark** [comment]
Any progress here @nicinabox?

**Comment by nicinabox** [comment]
@davidtheclark Thanks for the ping. I've been tied up the last few weeks but hoping to get back around to this this week.

**Comment by jeddy3** [comment]
@nicinabox & @davidtheclark I hope to take a stab a continuing this over the next few days... just letting you guys know so that we don't duplicate effort :)

@nicinabox Great job with the "whirlygig that copies and parses the docs for use on the site" btw :) Converting the repo docs into something that can be consumed by a static site generate is the lynch-pin of all this.

**Comment by davidtheclark** [comment]
@jeddy3 Ok, go for it. I have a bunch of open-source things to work on right now (including a bunch for stylelint); but if those slow down I might get involved, too, to help it get done. I'd like to get the website done and then promote the tool a little more aggressively.

**Comment by nicinabox** [comment]
@jeddy3 Go for it :+1:
